# Generated by Django 5.2.5 on 2025-08-29 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='total',
        ),
        migrations.AddField(
            model_name='lista',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
