# Generated by Django 5.2.5 on 2025-08-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0002_remove_lista_total_lista_criado_em'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='lista',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
